// Code generated by "stringer -type=Vote"; DO NOT EDIT.

package tcommit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VoteUnkown-0]
	_ = x[VotePrepared-1]
	_ = x[VoteAborted-2]
}

const _Vote_name = "VoteUnkownVotePreparedVoteAborted"

var _Vote_index = [...]uint8{0, 10, 22, 33}

func (i Vote) String() string {
	if i >= Vote(len(_Vote_index)-1) {
		return "Vote(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Vote_name[_Vote_index[i]:_Vote_index[i+1]]
}
