// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: proposer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PromiseRequest to proposer
type PromiseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg *Px1B `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *PromiseRequest) Reset() {
	*x = PromiseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proposer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PromiseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromiseRequest) ProtoMessage() {}

func (x *PromiseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proposer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromiseRequest.ProtoReflect.Descriptor instead.
func (*PromiseRequest) Descriptor() ([]byte, []int) {
	return file_proposer_proto_rawDescGZIP(), []int{0}
}

func (x *PromiseRequest) GetMsg() *Px1B {
	if x != nil {
		return x.Msg
	}
	return nil
}

// PromiseResponse from proposer
type PromiseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PromiseResponse) Reset() {
	*x = PromiseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proposer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PromiseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromiseResponse) ProtoMessage() {}

func (x *PromiseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proposer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromiseResponse.ProtoReflect.Descriptor instead.
func (*PromiseResponse) Descriptor() ([]byte, []int) {
	return file_proposer_proto_rawDescGZIP(), []int{1}
}

// AcceptedRequest to proposer
type AcceptedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg *Px2B `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *AcceptedRequest) Reset() {
	*x = AcceptedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proposer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedRequest) ProtoMessage() {}

func (x *AcceptedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proposer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedRequest.ProtoReflect.Descriptor instead.
func (*AcceptedRequest) Descriptor() ([]byte, []int) {
	return file_proposer_proto_rawDescGZIP(), []int{2}
}

func (x *AcceptedRequest) GetMsg() *Px2B {
	if x != nil {
		return x.Msg
	}
	return nil
}

// AcceptedResponse from proposer
type AcceptedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AcceptedResponse) Reset() {
	*x = AcceptedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proposer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedResponse) ProtoMessage() {}

func (x *AcceptedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proposer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedResponse.ProtoReflect.Descriptor instead.
func (*AcceptedResponse) Descriptor() ([]byte, []int) {
	return file_proposer_proto_rawDescGZIP(), []int{3}
}

// RejectRequest to proposer
type RejectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ballot *Ballot `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
}

func (x *RejectRequest) Reset() {
	*x = RejectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proposer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RejectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRequest) ProtoMessage() {}

func (x *RejectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proposer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRequest.ProtoReflect.Descriptor instead.
func (*RejectRequest) Descriptor() ([]byte, []int) {
	return file_proposer_proto_rawDescGZIP(), []int{4}
}

func (x *RejectRequest) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

// RejectResponse from proposer
type RejectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RejectResponse) Reset() {
	*x = RejectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proposer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RejectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectResponse) ProtoMessage() {}

func (x *RejectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proposer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectResponse.ProtoReflect.Descriptor instead.
func (*RejectResponse) Descriptor() ([]byte, []int) {
	return file_proposer_proto_rawDescGZIP(), []int{5}
}

var File_proposer_proto protoreflect.FileDescriptor

var file_proposer_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x64, 0x65, 0x67, 0x69, 0x74, 0x78, 0x2e, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x1a, 0x0b,
	0x70, 0x61, 0x78, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x0e, 0x50,
	0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x65, 0x67,
	0x69, 0x74, 0x78, 0x2e, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x2e, 0x50, 0x78, 0x31, 0x42, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x11, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x37, 0x0a, 0x0f, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x65, 0x67, 0x69, 0x74, 0x78, 0x2e,
	0x70, 0x61, 0x78, 0x6f, 0x73, 0x2e, 0x50, 0x78, 0x32, 0x42, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22,
	0x12, 0x0a, 0x10, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x3d, 0x0a, 0x0d, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x06, 0x62, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x65, 0x67, 0x69, 0x74, 0x78, 0x2e, 0x70, 0x61,
	0x78, 0x6f, 0x73, 0x2e, 0x42, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x52, 0x06, 0x62, 0x61, 0x6c, 0x6c,
	0x6f, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xe9, 0x01, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x6d,
	0x69, 0x73, 0x65, 0x12, 0x1c, 0x2e, 0x64, 0x65, 0x67, 0x69, 0x74, 0x78, 0x2e, 0x70, 0x61, 0x78,
	0x6f, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x64, 0x65, 0x67, 0x69, 0x74, 0x78, 0x2e, 0x70, 0x61, 0x78, 0x6f, 0x73,
	0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x49, 0x0a, 0x08, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x1d, 0x2e, 0x64,
	0x65, 0x67, 0x69, 0x74, 0x78, 0x2e, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x64, 0x65,
	0x67, 0x69, 0x74, 0x78, 0x2e, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x06, 0x52,
	0x65, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1b, 0x2e, 0x64, 0x65, 0x67, 0x69, 0x74, 0x78, 0x2e, 0x70,
	0x61, 0x78, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x64, 0x65, 0x67, 0x69, 0x74, 0x78, 0x2e, 0x70, 0x61, 0x78, 0x6f,
	0x73, 0x2e, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x23, 0x5a, 0x21, 0x63, 0x71, 0x66, 0x6e, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x64, 0x65, 0x67,
	0x69, 0x74, 0x78, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proposer_proto_rawDescOnce sync.Once
	file_proposer_proto_rawDescData = file_proposer_proto_rawDesc
)

func file_proposer_proto_rawDescGZIP() []byte {
	file_proposer_proto_rawDescOnce.Do(func() {
		file_proposer_proto_rawDescData = protoimpl.X.CompressGZIP(file_proposer_proto_rawDescData)
	})
	return file_proposer_proto_rawDescData
}

var file_proposer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proposer_proto_goTypes = []interface{}{
	(*PromiseRequest)(nil),   // 0: degitx.paxos.PromiseRequest
	(*PromiseResponse)(nil),  // 1: degitx.paxos.PromiseResponse
	(*AcceptedRequest)(nil),  // 2: degitx.paxos.AcceptedRequest
	(*AcceptedResponse)(nil), // 3: degitx.paxos.AcceptedResponse
	(*RejectRequest)(nil),    // 4: degitx.paxos.RejectRequest
	(*RejectResponse)(nil),   // 5: degitx.paxos.RejectResponse
	(*Px1B)(nil),             // 6: degitx.paxos.Px1B
	(*Px2B)(nil),             // 7: degitx.paxos.Px2B
	(*Ballot)(nil),           // 8: degitx.paxos.Ballot
}
var file_proposer_proto_depIdxs = []int32{
	6, // 0: degitx.paxos.PromiseRequest.msg:type_name -> degitx.paxos.Px1B
	7, // 1: degitx.paxos.AcceptedRequest.msg:type_name -> degitx.paxos.Px2B
	8, // 2: degitx.paxos.RejectRequest.ballot:type_name -> degitx.paxos.Ballot
	0, // 3: degitx.paxos.ProposerService.Promise:input_type -> degitx.paxos.PromiseRequest
	2, // 4: degitx.paxos.ProposerService.Accepted:input_type -> degitx.paxos.AcceptedRequest
	4, // 5: degitx.paxos.ProposerService.Reject:input_type -> degitx.paxos.RejectRequest
	1, // 6: degitx.paxos.ProposerService.Promise:output_type -> degitx.paxos.PromiseResponse
	3, // 7: degitx.paxos.ProposerService.Accepted:output_type -> degitx.paxos.AcceptedResponse
	5, // 8: degitx.paxos.ProposerService.Reject:output_type -> degitx.paxos.RejectResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proposer_proto_init() }
func file_proposer_proto_init() {
	if File_proposer_proto != nil {
		return
	}
	file_paxos_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proposer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PromiseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proposer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PromiseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proposer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proposer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proposer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RejectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proposer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RejectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proposer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proposer_proto_goTypes,
		DependencyIndexes: file_proposer_proto_depIdxs,
		MessageInfos:      file_proposer_proto_msgTypes,
	}.Build()
	File_proposer_proto = out.File
	file_proposer_proto_rawDesc = nil
	file_proposer_proto_goTypes = nil
	file_proposer_proto_depIdxs = nil
}
