---
name: CI
"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-20.04]
        go: [1.15, 1.16]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: arduino/setup-protoc@v1.1.2
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        run: make build
  test:
    name: Test
    needs: build
    strategy:
      matrix:
        os: [ubuntu-20.04]
        go: [1.15, 1.16]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: arduino/setup-protoc@v1.1.2
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: make test
  race:
    name: Test-race
    needs: build
    strategy:
      matrix:
        os: [ubuntu-20.04]
        go: [1.16]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: arduino/setup-protoc@v1.1.2
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: make test-race
  golangci:
    name: Lint
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: arduino/setup-protoc@v1.1.2
      - uses: actions/checkout@v2
      - run: make proto
      - name: Lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.36
