---
name: CI
"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14.7
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: arduino/setup-protoc@master
      - name: Generete proto
        run: |
          go get -u github.com/golang/protobuf/protoc-gen-go
          protoc --proto_path=./proto --go_out=plugins=grpc:./proto/go/degitxpb --go_opt=paths=source_relative ./proto/*.proto
      - name: Build
        run: |
          go build -v
          go build -v ./cmd/node
      - name: Test
        run: go test -v
